version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.ReactUI
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.API
    container_name: backend-container
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb  # Assuming you have a MongoDB service defined as well

  mongodb:
    image: mongo
    container_name: mongo-container
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
